### ISSUE TITLE
CSS Grid ?

### ISSUE THREAD

**Issue by Gi972** [moarwick/react-super-styled#12]
Hello @moarwick,
 
Your tool is very great, your flexbox  shorcut sytem is cool.
Have you plan for implement also Css Grid?

Thanks

**Comment by moarwick** [comment]
thanks @Gi972. makes sense, would love to.. need to "learn" CSS Grid a bit more, but should get to it soon 👍

**Comment by Gi972** [comment]
Great!

:+1:  Thanks I hope you can do as simplest as Flex and FlexItem ;-)
